#
# Copyright (C) 2015-2016 Orange
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

logging.level.org.springframework.security: INFO
logging.level.org.apache.http.wire: INFO
logging.level.com.orange.clara.cloud.services.sandbox.ui: INFO

sandbox:
  service:
    url: ${SANDBOX_SERVICE_URL:http://localhost:8081}
    healthContextPath: /manage/health
zuul:
  routes:
    sandboxes:
      path: /v1/sandboxes/**
      url: ${SANDBOX_SERVICE_URL:http://localhost:8081}/v1/sandboxes
#enableSslCertificateCheck: true
security:
  enable_csrf: true
  require_ssl: true
  sessions: IF_REQUIRED

  user:
    name: admin
    password: ${ADMIN_PASSWORD:sandbox-admin}
  oauth2:
    client:
      accessTokenUri: ${LOGIN_URL:http://localhost}/oauth/token
      userAuthorizationUri: ${LOGIN_URL:http://localhost}/oauth/authorize
      clientAuthenticationScheme: header
      clientId:
      clientSecret:
    resource:
       jwt:
          key-uri: ${LOGIN_URL:http://localhost}/token_key
endpoints:
  actuator:
    sensitive: true
management:
  security:
    enabled: true
  context-path: /manage
server:
  session:
    timeout: 180
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

