logging.level.org.springframework.security: INFO
logging.level.org.apache.http.wire: INFO

zuul:
  routes:
    sandboxes:
      path: /v1/sandboxes/**
      url: ${SANDBOX_SERVICE_URL:http://localhost:8081}/v1/sandboxes
#enableSslCertificateCheck: true
security:
  enable_csrf: true
  require_ssl: true
  sessions: IF_REQUIRED
  user:
    name: admin
    password: ${ADMIN_PASSWORD:sandbox-admin}
  oauth2:
    client:
      accessTokenUri: ${LOGIN_URL:http://localhost}/oauth/token
      userAuthorizationUri: ${LOGIN_URL:http://localhost}/oauth/authorize
      clientAuthenticationScheme: header
      clientId:
      clientSecret:
    resource:
       jwt:
          keyValue: ${SECURITY_OAUTH2_RESOURCE_JWT_KEY_VALUE:no_key_defined}
endpoints:
  actuator:
    sensitive: true
management:
  security:
    enabled: true
  context-path: /manage
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto